/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Nov 3, 2010, 3:51:13 PM
 */

package newpackage;

/**
 *
 * @author Rav
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/play.gif")); // NOI18N
        jButton1.setBorderPainted(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 10, 48, 44);

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/prev.gif")); // NOI18N
        jButton2.setBorderPainted(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 10, 48, 44);

        jButton3.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/next.gif")); // NOI18N
        jButton3.setBorderPainted(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 10, 48, 44);

        jButton4.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/stop.gif")); // NOI18N
        jButton4.setBorderPainted(false);
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 10, 48, 44);

        jButton5.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/pause.png")); // NOI18N
        jButton5.setBorderPainted(false);
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 10, 48, 44);

        jButton6.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/tray.gif")); // NOI18N
        jButton6.setBorderPainted(false);
        getContentPane().add(jButton6);
        jButton6.setBounds(300, 10, 48, 44);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(100, 60, 190, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MaciTunesController/Bin/img/2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 390, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

}
