/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame4.java
 *
 * Created on Oct 31, 2010, 12:12:31 AM
 */

package gui;

/**
 *
 * @author Rav
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /** Creates new form NewJFrame4 */
    public NewJFrame4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(390, 368));
        setMinimumSize(new java.awt.Dimension(390, 368));
        setPreferredSize(new java.awt.Dimension(390, 368));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel1.setText("GTBIT Informer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(109, 20, 191, 61);

        jLabel2.setText("Enroll. No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 66, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 100, 171, 28);

        jLabel3.setText("Email ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 52, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 150, 171, 28);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 59, 16);

        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 260, 114, 16);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(180, 200, 171, 28);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(180, 250, 171, 28);

        jButton1.setText("Submit");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 320, 88, 29);

        jButton2.setText("Reset");
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 320, 78, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/gtbitattendance/bg.jpeg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 390, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
