/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Icon.java
 *
 * Created on Mar 12, 2011, 11:57:07 AM
 */

package MainScreenTesting;

/**
 *
 * @author Rav
 */
public class Icon extends javax.swing.JPanel {

    /** Creates new form Icon */
    public Icon() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(jProgressBar1);
        jProgressBar1.setBounds(10, 40, 30, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/Rav/Desktop/logo_ws.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 60, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}
