/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Oct 10, 2010, 1:21:44 AM
 */

package newpackage;

/**
 *
 * @author Rav
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 320));
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 410, 90);

        jButton1.setText("Tweet");
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 10, 81, 29);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel2.setFont(new java.awt.Font("Zapfino", 1, 18));
        jLabel2.setText("R Tweet");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 0, 100, 61);

        jLabel3.setFont(new java.awt.Font("American Typewriter", 1, 13));
        jLabel3.setText("140");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 170, 27, 17);

        jButton2.setText("Profile");
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 250, 84, 29);

        jButton3.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MyTweetApp/delete.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(-10, 0, 60, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MyTweetApp/bg.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 480, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
