/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on Oct 10, 2010, 3:46:10 PM
 */

package newpackage;

/**
 *
 * @author Rav
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /** Creates new form NewJFrame1 */
    public NewJFrame1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Zapfino", 1, 24));
        jLabel1.setText("R Tweet");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 140, 82);

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 16));
        jLabel2.setText("Get PIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 140, 64, 21);

        jButton1.setText("@ URL");
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 160, 83, 29);

        jLabel3.setFont(new java.awt.Font("American Typewriter", 1, 16));
        jLabel3.setText("Enter PIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(188, 300, 90, 21);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 290, 143, 30);

        jButton2.setText("Verify");
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 330, 80, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/Rav/NetBeansProjects/MyTweetApp/signUpBg.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 520, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
