package jtunes;

// GENERATED. DO NOT MODIFY
import com4j.*;

/**
 * IITOperationStatus Interface
 */
@IID("{206479C9-FE32-4F9B-A18A-475AC939B479}")
public interface IITOperationStatus extends Com4jObject {
    /**
     * True if the operation is still in progress.
     */
    @VTID(7)
    boolean inProgress();

    /**
     * Returns a collection containing the tracks that were generated by the operation.
     */
    @VTID(8)
    IITTrackCollection tracks();

}
